-- HOTEL_REGIMEN
USE [GD2C2014]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[CONTROL_ZETA].[FK_HOTEL_REGIMEN_HOTEL_ID]') AND parent_object_id = OBJECT_ID(N'[CONTROL_ZETA].[HOTEL_REGIMEN]'))
ALTER TABLE [CONTROL_ZETA].[HOTEL_REGIMEN] DROP CONSTRAINT [FK_HOTEL_REGIMEN_HOTEL_ID]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[CONTROL_ZETA].[FK_HOTEL_REGIMEN_REG_ID]') AND parent_object_id = OBJECT_ID(N'[CONTROL_ZETA].[HOTEL_REGIMEN]'))
ALTER TABLE [CONTROL_ZETA].[HOTEL_REGIMEN] DROP CONSTRAINT [FK_HOTEL_REGIMEN_REG_ID]
GO

USE [GD2C2014]
GO

/****** Object:  Table [CONTROL_ZETA].[HOTEL_REGIMEN]    Script Date: 10/06/2014 02:34:41 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[CONTROL_ZETA].[HOTEL_REGIMEN]') AND type in (N'U'))
DROP TABLE [CONTROL_ZETA].[HOTEL_REGIMEN]
GO


-- RESERVA_HABITACION
USE [GD2C2014]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[CONTROL_ZETA].[FK_RESERVA_HABITACION_HAB_NRO]') AND parent_object_id = OBJECT_ID(N'[CONTROL_ZETA].[RESERVA_HABITACION]'))
ALTER TABLE [CONTROL_ZETA].[RESERVA_HABITACION] DROP CONSTRAINT [FK_RESERVA_HABITACION_HAB_NRO]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[CONTROL_ZETA].[FK_RESERVA_ID]') AND parent_object_id = OBJECT_ID(N'[CONTROL_ZETA].[RESERVA_HABITACION]'))
ALTER TABLE [CONTROL_ZETA].[RESERVA_HABITACION] DROP CONSTRAINT [FK_RESERVA_ID]
GO

USE [GD2C2014]
GO

/****** Object:  Table [CONTROL_ZETA].[RESERVA_HABITACION]    Script Date: 10/06/2014 02:39:57 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[CONTROL_ZETA].[RESERVA_HABITACION]') AND type in (N'U'))
DROP TABLE [CONTROL_ZETA].[RESERVA_HABITACION]
GO



-- ESTADIA_HAB_CON
USE [GD2C2014]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[CONTROL_ZETA].[FK_EST_HAB_CON_CONSUMO_ID]') AND parent_object_id = OBJECT_ID(N'[CONTROL_ZETA].[ESTADIA_HAB_CON]'))
ALTER TABLE [CONTROL_ZETA].[ESTADIA_HAB_CON] DROP CONSTRAINT [FK_EST_HAB_CON_CONSUMO_ID]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[CONTROL_ZETA].[FK_EST_HAB_CON_ESTADIA_ID]') AND parent_object_id = OBJECT_ID(N'[CONTROL_ZETA].[ESTADIA_HAB_CON]'))
ALTER TABLE [CONTROL_ZETA].[ESTADIA_HAB_CON] DROP CONSTRAINT [FK_EST_HAB_CON_ESTADIA_ID]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[CONTROL_ZETA].[FK_EST_HAB_CON_HABITACION_ID]') AND parent_object_id = OBJECT_ID(N'[CONTROL_ZETA].[ESTADIA_HAB_CON]'))
ALTER TABLE [CONTROL_ZETA].[ESTADIA_HAB_CON] DROP CONSTRAINT [FK_EST_HAB_CON_HABITACION_ID]
GO

USE [GD2C2014]
GO

/****** Object:  Table [CONTROL_ZETA].[ESTADIA_HAB_CON]    Script Date: 10/06/2014 02:40:16 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[CONTROL_ZETA].[ESTADIA_HAB_CON]') AND type in (N'U'))
DROP TABLE [CONTROL_ZETA].[ESTADIA_HAB_CON]
GO




-- ESTADIA_CLIENTE

USE [GD2C2014]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[CONTROL_ZETA].[FK_CLIENTE_ID]') AND parent_object_id = OBJECT_ID(N'[CONTROL_ZETA].[ESTADIA_CLIENTE]'))
ALTER TABLE [CONTROL_ZETA].[ESTADIA_CLIENTE] DROP CONSTRAINT [FK_CLIENTE_ID]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[CONTROL_ZETA].[FK_EST_ID]') AND parent_object_id = OBJECT_ID(N'[CONTROL_ZETA].[ESTADIA_CLIENTE]'))
ALTER TABLE [CONTROL_ZETA].[ESTADIA_CLIENTE] DROP CONSTRAINT [FK_EST_ID]
GO

USE [GD2C2014]
GO

/****** Object:  Table [CONTROL_ZETA].[ESTADIA_CLIENTE]    Script Date: 10/06/2014 02:40:49 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[CONTROL_ZETA].[ESTADIA_CLIENTE]') AND type in (N'U'))
DROP TABLE [CONTROL_ZETA].[ESTADIA_CLIENTE]
GO

-- USR_ROL
USE [GD2C2014]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[CONTROL_ZETA].[FK_USR_ROL_ID]') AND parent_object_id = OBJECT_ID(N'[CONTROL_ZETA].[USR_ROL]'))
ALTER TABLE [CONTROL_ZETA].[USR_ROL] DROP CONSTRAINT [FK_USR_ROL_ID]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[CONTROL_ZETA].[FK_USR_ROL_USERNAME]') AND parent_object_id = OBJECT_ID(N'[CONTROL_ZETA].[USR_ROL]'))
ALTER TABLE [CONTROL_ZETA].[USR_ROL] DROP CONSTRAINT [FK_USR_ROL_USERNAME]
GO

USE [GD2C2014]
GO

/****** Object:  Table [CONTROL_ZETA].[USR_ROL]    Script Date: 10/06/2014 02:41:10 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[CONTROL_ZETA].[USR_ROL]') AND type in (N'U'))
DROP TABLE [CONTROL_ZETA].[USR_ROL]
GO




-- USR_HOTEL
USE [GD2C2014]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[CONTROL_ZETA].[FK_HOTEL_ID]') AND parent_object_id = OBJECT_ID(N'[CONTROL_ZETA].[USR_HOTEL]'))
ALTER TABLE [CONTROL_ZETA].[USR_HOTEL] DROP CONSTRAINT [FK_HOTEL_ID]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[CONTROL_ZETA].[FK_USR_USERNAME]') AND parent_object_id = OBJECT_ID(N'[CONTROL_ZETA].[USR_HOTEL]'))
ALTER TABLE [CONTROL_ZETA].[USR_HOTEL] DROP CONSTRAINT [FK_USR_USERNAME]
GO

USE [GD2C2014]
GO

/****** Object:  Table [CONTROL_ZETA].[USR_HOTEL]    Script Date: 10/06/2014 02:41:32 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[CONTROL_ZETA].[USR_HOTEL]') AND type in (N'U'))
DROP TABLE [CONTROL_ZETA].[USR_HOTEL]
GO



-- ROL_FUNC
USE [GD2C2014]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[CONTROL_ZETA].[FK_FUNC_ID]') AND parent_object_id = OBJECT_ID(N'[CONTROL_ZETA].[ROL_FUNC]'))
ALTER TABLE [CONTROL_ZETA].[ROL_FUNC] DROP CONSTRAINT [FK_FUNC_ID]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[CONTROL_ZETA].[FK_ROL_ID]') AND parent_object_id = OBJECT_ID(N'[CONTROL_ZETA].[ROL_FUNC]'))
ALTER TABLE [CONTROL_ZETA].[ROL_FUNC] DROP CONSTRAINT [FK_ROL_ID]
GO

USE [GD2C2014]
GO

/****** Object:  Table [CONTROL_ZETA].[ROL_FUNC]    Script Date: 10/06/2014 02:41:59 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[CONTROL_ZETA].[ROL_FUNC]') AND type in (N'U'))
DROP TABLE [CONTROL_ZETA].[ROL_FUNC]
GO



-- ITEM_FACTURA
USE [GD2C2014]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[CONTROL_ZETA].[FK_ITEM_FACTURA_NRO]') AND parent_object_id = OBJECT_ID(N'[CONTROL_ZETA].[ITEM_FACTURA]'))
ALTER TABLE [CONTROL_ZETA].[ITEM_FACTURA] DROP CONSTRAINT [FK_ITEM_FACTURA_NRO]
GO

USE [GD2C2014]
GO

/****** Object:  Table [CONTROL_ZETA].[ITEM_FACTURA]    Script Date: 10/06/2014 02:42:15 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[CONTROL_ZETA].[ITEM_FACTURA]') AND type in (N'U'))
DROP TABLE [CONTROL_ZETA].[ITEM_FACTURA]
GO



-- FACTURA
USE [GD2C2014]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[CONTROL_ZETA].[FK_FACT_EST_ID]') AND parent_object_id = OBJECT_ID(N'[CONTROL_ZETA].[FACTURA]'))
ALTER TABLE [CONTROL_ZETA].[FACTURA] DROP CONSTRAINT [FK_FACT_EST_ID]
GO

USE [GD2C2014]
GO

/****** Object:  Table [CONTROL_ZETA].[FACTURA]    Script Date: 10/06/2014 02:42:33 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[CONTROL_ZETA].[FACTURA]') AND type in (N'U'))
DROP TABLE [CONTROL_ZETA].[FACTURA]
GO




-- ESTADIA

USE [GD2C2014]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[CONTROL_ZETA].[FK_ESTA_RESERVA_ID]') AND parent_object_id = OBJECT_ID(N'[CONTROL_ZETA].[ESTADIA]'))
ALTER TABLE [CONTROL_ZETA].[ESTADIA] DROP CONSTRAINT [FK_ESTA_RESERVA_ID]
GO

USE [GD2C2014]
GO

/****** Object:  Table [CONTROL_ZETA].[ESTADIA]    Script Date: 10/06/2014 02:42:49 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[CONTROL_ZETA].[ESTADIA]') AND type in (N'U'))
DROP TABLE [CONTROL_ZETA].[ESTADIA]
GO




-- RESERVA
USE [GD2C2014]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[CONTROL_ZETA].[FK_RES_CLIENTE_ID]') AND parent_object_id = OBJECT_ID(N'[CONTROL_ZETA].[RESERVA]'))
ALTER TABLE [CONTROL_ZETA].[RESERVA] DROP CONSTRAINT [FK_RES_CLIENTE_ID]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[CONTROL_ZETA].[FK_RESERVA_ID_HOTEL]') AND parent_object_id = OBJECT_ID(N'[CONTROL_ZETA].[RESERVA]'))
ALTER TABLE [CONTROL_ZETA].[RESERVA] DROP CONSTRAINT [FK_RESERVA_ID_HOTEL]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[CONTROL_ZETA].[FK_RESERVA_ID_REGIMEN]') AND parent_object_id = OBJECT_ID(N'[CONTROL_ZETA].[RESERVA]'))
ALTER TABLE [CONTROL_ZETA].[RESERVA] DROP CONSTRAINT [FK_RESERVA_ID_REGIMEN]
GO

USE [GD2C2014]
GO

/****** Object:  Table [CONTROL_ZETA].[RESERVA]    Script Date: 10/06/2014 02:43:28 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[CONTROL_ZETA].[RESERVA]') AND type in (N'U'))
DROP TABLE [CONTROL_ZETA].[RESERVA]
GO



-- HABITACION

USE [GD2C2014]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[CONTROL_ZETA].[FK_HAB_ID_HOTEL]') AND parent_object_id = OBJECT_ID(N'[CONTROL_ZETA].[HABITACION]'))
ALTER TABLE [CONTROL_ZETA].[HABITACION] DROP CONSTRAINT [FK_HAB_ID_HOTEL]
GO

USE [GD2C2014]
GO

/****** Object:  Table [CONTROL_ZETA].[HABITACION]    Script Date: 10/06/2014 02:43:48 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[CONTROL_ZETA].[HABITACION]') AND type in (N'U'))
DROP TABLE [CONTROL_ZETA].[HABITACION]
GO




-- HOTEL_CIERRE

USE [GD2C2014]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[CONTROL_ZETA].[FK_HOTEL_ID_CIERRE]') AND parent_object_id = OBJECT_ID(N'[CONTROL_ZETA].[HOTEL_CIERRE]'))
ALTER TABLE [CONTROL_ZETA].[HOTEL_CIERRE] DROP CONSTRAINT [FK_HOTEL_ID_CIERRE]
GO

USE [GD2C2014]
GO

/****** Object:  Table [CONTROL_ZETA].[HOTEL_CIERRE]    Script Date: 10/06/2014 02:44:04 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[CONTROL_ZETA].[HOTEL_CIERRE]') AND type in (N'U'))
DROP TABLE [CONTROL_ZETA].[HOTEL_CIERRE]
GO



-- HOTEL
USE [GD2C2014]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[CONTROL_ZETA].[FK_HOTEL_PAIS]') AND parent_object_id = OBJECT_ID(N'[CONTROL_ZETA].[HOTEL]'))
ALTER TABLE [CONTROL_ZETA].[HOTEL] DROP CONSTRAINT [FK_HOTEL_PAIS]
GO

USE [GD2C2014]
GO

/****** Object:  Table [CONTROL_ZETA].[HOTEL]    Script Date: 10/06/2014 02:44:20 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[CONTROL_ZETA].[HOTEL]') AND type in (N'U'))
DROP TABLE [CONTROL_ZETA].[HOTEL]
GO



-- USUARIO
USE [GD2C2014]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[CONTROL_ZETA].[FK_USR_TIPO_DOC]') AND parent_object_id = OBJECT_ID(N'[CONTROL_ZETA].[USUARIO]'))
ALTER TABLE [CONTROL_ZETA].[USUARIO] DROP CONSTRAINT [FK_USR_TIPO_DOC]
GO

USE [GD2C2014]
GO

/****** Object:  Table [CONTROL_ZETA].[USUARIO]    Script Date: 10/06/2014 02:44:55 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[CONTROL_ZETA].[USUARIO]') AND type in (N'U'))
DROP TABLE [CONTROL_ZETA].[USUARIO]
GO



-- CLIENTE

USE [GD2C2014]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[CONTROL_ZETA].[FK_LOCALIDAD]') AND parent_object_id = OBJECT_ID(N'[CONTROL_ZETA].[CLIENTE]'))
ALTER TABLE [CONTROL_ZETA].[CLIENTE] DROP CONSTRAINT [FK_LOCALIDAD]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[CONTROL_ZETA].[FK_NAC]') AND parent_object_id = OBJECT_ID(N'[CONTROL_ZETA].[CLIENTE]'))
ALTER TABLE [CONTROL_ZETA].[CLIENTE] DROP CONSTRAINT [FK_NAC]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[CONTROL_ZETA].[FK_PAIS]') AND parent_object_id = OBJECT_ID(N'[CONTROL_ZETA].[CLIENTE]'))
ALTER TABLE [CONTROL_ZETA].[CLIENTE] DROP CONSTRAINT [FK_PAIS]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[CONTROL_ZETA].[FK_TIPO_DOC]') AND parent_object_id = OBJECT_ID(N'[CONTROL_ZETA].[CLIENTE]'))
ALTER TABLE [CONTROL_ZETA].[CLIENTE] DROP CONSTRAINT [FK_TIPO_DOC]
GO

USE [GD2C2014]
GO

/****** Object:  Table [CONTROL_ZETA].[CLIENTE]    Script Date: 10/06/2014 02:45:11 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[CONTROL_ZETA].[CLIENTE]') AND type in (N'U'))
DROP TABLE [CONTROL_ZETA].[CLIENTE]
GO




-- REGIMEN
USE [GD2C2014]
GO

/****** Object:  Table [CONTROL_ZETA].[REGIMEN]    Script Date: 10/06/2014 02:45:29 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[CONTROL_ZETA].[REGIMEN]') AND type in (N'U'))
DROP TABLE [CONTROL_ZETA].[REGIMEN]
GO



-- CONSUMIBLE
USE [GD2C2014]
GO

/****** Object:  Table [CONTROL_ZETA].[CONSUMIBLE]    Script Date: 10/06/2014 02:46:00 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[CONTROL_ZETA].[CONSUMIBLE]') AND type in (N'U'))
DROP TABLE [CONTROL_ZETA].[CONSUMIBLE]
GO



-- TIPO_HAB

USE [GD2C2014]
GO

/****** Object:  Table [CONTROL_ZETA].[TIPO_HAB]    Script Date: 10/06/2014 02:46:20 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[CONTROL_ZETA].[TIPO_HAB]') AND type in (N'U'))
DROP TABLE [CONTROL_ZETA].[TIPO_HAB]
GO



-- ROL
USE [GD2C2014]
GO

/****** Object:  Table [CONTROL_ZETA].[ROL]    Script Date: 10/06/2014 02:46:48 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[CONTROL_ZETA].[ROL]') AND type in (N'U'))
DROP TABLE [CONTROL_ZETA].[ROL]
GO



-- LOCALIDAD
USE [GD2C2014]
GO

/****** Object:  Table [CONTROL_ZETA].[LOCALIDAD]    Script Date: 10/06/2014 02:47:08 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[CONTROL_ZETA].[LOCALIDAD]') AND type in (N'U'))
DROP TABLE [CONTROL_ZETA].[LOCALIDAD]
GO



-- FUNCIONALIDAD
USE [GD2C2014]
GO

/****** Object:  Table [CONTROL_ZETA].[FUNCIONALIDAD]    Script Date: 10/06/2014 02:47:25 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[CONTROL_ZETA].[FUNCIONALIDAD]') AND type in (N'U'))
DROP TABLE [CONTROL_ZETA].[FUNCIONALIDAD]
GO



-- TIPO_DOC
USE [GD2C2014]
GO

/****** Object:  Table [CONTROL_ZETA].[TIPO_DOC]    Script Date: 10/06/2014 02:47:54 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[CONTROL_ZETA].[TIPO_DOC]') AND type in (N'U'))
DROP TABLE [CONTROL_ZETA].[TIPO_DOC]
GO



-- NACIONALIDAD

USE [GD2C2014]
GO

/****** Object:  Table [CONTROL_ZETA].[NACIONALIDAD]    Script Date: 10/06/2014 02:48:14 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[CONTROL_ZETA].[NACIONALIDAD]') AND type in (N'U'))
DROP TABLE [CONTROL_ZETA].[NACIONALIDAD]
GO



-- PAIS
USE [GD2C2014]
GO

/****** Object:  Table [CONTROL_ZETA].[PAIS]    Script Date: 10/06/2014 02:48:33 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[CONTROL_ZETA].[PAIS]') AND type in (N'U'))
DROP TABLE [CONTROL_ZETA].[PAIS]
GO














