---Referencia Accion
--1:Alta-Insert
--2:Modificacion-Update
--3:Borrado-Delete

----ABM ROL-3 (Deberia cargar la tabla ROL, ROL_FUNC)
CREATE PROCEDURE CONTROL_ZETA.SP_ABM_ROL (@accion SMALLINT,@nombre varchar(20),@estado varchar(1))
as
begin
end;
---IMPORTANTE:Se tendria que hacer otro SP para asociar el ROL con la Funcionalidad y que desde la app se ejecute varias veces


---ASIGNACION DE FUNCIONES A ROL-3 (Carga tabla ROL_FUNC)
CREATE PROCEDURE CONTROL_ZETA.SP_ROL_FUNC(@accion SMALLINT,@rol_id TINYINT, @func_id TINYINT)
AS
BEGIN
END;

---ABM HOTEL(Tabla Hotel)-2
CREATE PROCEDURE CONTROL_ZETA.SP_ABM_HOTEL()
AS
BEGIN
END;
---ABM HABITACION(Tabla habitaciones)-2
CREATE PROCEDURE CONTROL_ZETA.SP_ABM_RESERVA()
AS
BEGIN
END;
---ALTA RESERVA(Tabla RESERVA, RESERVA_CLIENTE)-1
CREATE PROCEDURE CONTROL_ZETA.SP_ALTA_RESERVA()
AS
BEGIN
END;
---MODIFICACION RESERVA(Tabla RESERVA, RESERVA_CLIENTE)-1
CREATE PROCEDURE CONTROL_ZETA.SP_MODIF_RESERVA()
AS
BEGIN
END;
---CANCELAR RESERVA(Tabla RESERVA, RESERVA_CLIENTE)-1
CREATE PROCEDURE CONTROL_ZETA.SP_CANCELAR_RESERVA()
AS
BEGIN
END;

---REGISTRAR CONSUMIBLES(Tabla CON_EST_HAB)-2

