---Referencia Accion
--1:Alta-Insert
--2:Modificacion-Update
--3:Borrado-Delete

----ABM ROL-3 (Deberia cargar la tabla ROL, ROL_FUNC)
CREATE PROCEDURE CONTROL_ZETA.SP_ABM_ROL (@accion SMALLINT,@nombre varchar(20),@estado varchar(1))
as
begin
end;
---IMPORTANTE:Se tendria que hacer otro SP para asociar el ROL con la Funcionalidad y que desde la app se ejecute varias veces


---ASIGNACION DE FUNCIONES A ROL-3 (Carga tabla ROL_FUNC)
CREATE PROCEDURE CONTROL_ZETA.SP_ROL_FUNC(@accion SMALLINT,@rol_id TINYINT, @func_id TINYINT)
AS
BEGIN
END; 

---ABM HOTEL(Tabla Hotel)-2
CREATE PROCEDURE CONTROL_ZETA.SP_ABM_HOTEL()
AS
BEGIN
END;
---ABM HABITACION(Tabla habitaciones)-2
CREATE PROCEDURE CONTROL_ZETA.SP_ABM_RESERVA()
AS
BEGIN
END;
---ALTA RESERVA(Tabla RESERVA, RESERVA_CLIENTE)-1

--Verificacion de disponibilidad
CREATE FUNCTION CONTROL_ZETA.FN_VERIFICA_DISPONIBILIDAD(@hotel_id,@fe_desde,@fe_hasta,@cant_hab,@tipo_hab)
returns tinyint
AS
BEGIN

RETURNS(SELECT COUNT (H.HAB_ID) 
		FROM CONTROL_ZETA.HABITACION H 
		WHERE H.HAB_ID_HOTEL=@hotel_id AND
		H.HAB_ID_TIPO=@tipo_hab AND
		H.HAB_ID NOT IN (SELECT RH.HAB_ID 
						FROM CONTROL_ZETA.RESERVA_HABITACION RH 
						WHERE RH.RESERVA_ID NOT IN (SELECT R.RESERVA_ID 
													FROM CONTROL_ZETA.RESERVA R 
													WHERE R.RESERVA_FECHA_INICIO=@fe_desde AND 
													R.RESERVA_FECHA_HASTA=@fe_hasta AND
													R.RESERVA_ESTADO IN('RI','RC','RM')
												)))

END;

CREATE PROCEDURE CONTROL_ZETA.SP_ALTA_RESERVA(@hotel_id,@fe_desde,@fe_hasta,@tipo_reg_id,@cliente_id,@id_reserva OUTPUT)
AS
BEGIN
DECLARE

	SELECT (MAX(RESERVA_ID)+1) INTO @id_reserva FROM CONTROL_ZETA.RESERVA

	INSERT INTO CONTROL_ZETA.RESERVA (RESERVA_ID,RESERVA_FECHA_INICIO, RESERVA_FECHA_HASTA,RESERVA_ID_REGIMEN, RESERVA_ID_HOTEL, RESERVA_ESTADO, CLIENTE_ID)
	VALUES(@ID,,@fe_desde,@fe_hasta,@tipo_reg_id,@hotel_id,@cliente_id)
END;

CREATE PROCEDURE CONTROL_ZETA.SP_AGREGAR_HAB_RES(@id_reserva,@cant_hab,@tipo_hab)
AS
BEGIN
END;
---MODIFICACION RESERVA(Tabla RESERVA, RESERVA_CLIENTE)-1
CREATE PROCEDURE CONTROL_ZETA.SP_MODIF_RESERVA()
AS
BEGIN
END;
---CANCELAR RESERVA(Tabla RESERVA, RESERVA_CLIENTE)-1
CREATE PROCEDURE CONTROL_ZETA.SP_CANCELAR_RESERVA()
AS
BEGIN
END;

---REGISTRAR CONSUMIBLES(Tabla CON_EST_HAB)-2

